import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar for the 'docs' folder
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar for the 'references' folder
  referencesSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar for the 'custom-pages' folder
  customPagesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;