# This is the final, verified configuration for your project.

backend:
  name: git-gateway
  branch: main # IMPORTANT: Change this to 'master' if that is your branch name.

local_backend: true

# Global media folder for uploads not associated with a page.
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Documentation"
    label_singular: "Document"
    folder: "docs"
    create: true
    # This section is crucial for finding all your nested files.
    nested:
      depth: 100
      index_file: "index"
    summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
    extension: "md"
    path: "{{slug}}/index"
    # This allows images to be stored relative to the doc being edited.
    media_folder: ""
    public_folder: ""

  - name: "references"
    label: "API References"
    label_singular: "Reference"
    folder: "references"
    create: true
    nested:
      depth: 100
      index_file: "index"
    summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
    extension: "md"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""

  - name: "custom-pages"
    label: "Custom Pages"
    label_singular: "Custom Page"
    folder: "custom-pages"
    create: true
    nested:
      depth: 100
      index_file: "index"
    summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
    extension: "md"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""